# Generated by Django 4.1.1 on 2022-12-01 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='chater',
        ),
    ]
