# Generated by Django 4.1.1 on 2022-12-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_rename_room_chater'),
    ]

    operations = [
        migrations.CreateModel(
            name='ichater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10000)),
                ('message', models.CharField(max_length=100000000000000000)),
            ],
        ),
    ]
