# Generated by Django 4.1.1 on 2022-12-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_ichater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ichater',
            old_name='message',
            new_name='messageaya',
        ),
    ]
