# Generated by Django 4.1.1 on 2022-12-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_alter_ichater_messageaya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ichater',
            name='messageaya',
            field=models.CharField(default=None, max_length=100000000000000000, null=True),
        ),
    ]
